-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."News"
(
    "sophoraId" text NOT NULL,
    "externalId" text NOT NULL,
    title text NOT NULL,
    date date NOT NULL,
    "updateCheckUrl" json NOT NULL,
    "breakingNews" boolean NOT NULL,
    topline text NOT NULL,
    details json NOT NULL,
    detailsweb text NOT NULL,
    "shareURL" text NOT NULL,
    PRIMARY KEY ("sophoraId")
);

CREATE TABLE IF NOT EXISTS public."Tags"
(
    name text NOT NULL,
    PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public."Tags_News"
(
    "Tags_name" text NOT NULL,
    "News_sophoraId" text NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Types"
(
    name text NOT NULL
);

CREATE TABLE IF NOT EXISTS public."regionIds"
(
    "ID" bigint NOT NULL,
    name text NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."regionIds_News"
(
    "regionIds_ID" bigint NOT NULL,
    "News_sophoraId" text NOT NULL
);

ALTER TABLE IF EXISTS public."Tags_News"
    ADD FOREIGN KEY ("Tags_name")
    REFERENCES public."Tags" (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Tags_News"
    ADD FOREIGN KEY ("News_sophoraId")
    REFERENCES public."News" ("sophoraId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Types"
    ADD FOREIGN KEY (name)
    REFERENCES public."News" ("sophoraId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."regionIds_News"
    ADD FOREIGN KEY ("regionIds_ID")
    REFERENCES public."regionIds" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."regionIds_News"
    ADD FOREIGN KEY ("News_sophoraId")
    REFERENCES public."News" ("sophoraId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;