-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public."Types"
(
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Types_pkey" PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public."Tags"
(
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Tags_pkey" PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public."regionIds"
(
    "ID" bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "regionIds_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."News"
(
    "sophoraId" text COLLATE pg_catalog."default" NOT NULL,
    "externalId" text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    "updateCheckUrl" text COLLATE pg_catalog."default" NOT NULL,
    "breakingNews" boolean NOT NULL,
    topline text COLLATE pg_catalog."default" NOT NULL,
    details json NOT NULL,
    detailsweb text COLLATE pg_catalog."default" NOT NULL,
    "shareURL" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "News_pkey" PRIMARY KEY ("sophoraId"),
);

CREATE TABLE IF NOT EXISTS public."News_Tags"
(
    "News_sophoraId" text COLLATE pg_catalog."default" NOT NULL,
    "Tags_name" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "News_Tags_pkey" PRIMARY KEY ("News_sophoraId", "Tags_name"),
    FOREIGN KEY ("News_sophoraId") REFERENCES public."News" ("sophoraId") ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("Tags_name") REFERENCES public."Tags" (name) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public."News_regionIds"
(
    "News_sophoraId" text COLLATE pg_catalog."default" NOT NULL,
    "regionIds_ID" bigint NOT NULL,
    CONSTRAINT "News_regionIds_pkey" PRIMARY KEY ("News_sophoraId", "regionIds_ID"),
    FOREIGN KEY ("News_sophoraId") REFERENCES public."News" ("sophoraId") ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("regionIds_ID") REFERENCES public."regionIds" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION
);

END;
